Use Dockerhub credentials for workflow

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -6,7 +6,7 @@ on:
       - main
   pull_request:
     branches:
-      - '**'
+      - "**"
 
 env:
   IMAGE_REGISTRY: ghcr.io/hu1buerger/explorviz-span-service # TODO: set in github as env var
@@ -22,8 +22,8 @@ jobs:
       - name: Set up Java
         uses: actions/setup-java@v4
         with:
-          distribution: 'graalvm'
-          java-version: '21'
+          distribution: "graalvm"
+          java-version: "21"
 
       - name: Cache Gradle Packages
         uses: actions/cache@v4
@@ -47,8 +47,8 @@ jobs:
       - name: Set up Java
         uses: actions/setup-java@v4
         with:
-          distribution: 'graalvm'
-          java-version: '21'
+          distribution: "graalvm"
+          java-version: "21"
 
       - name: Cache Gradle Packages
         uses: actions/cache@v4
@@ -70,8 +70,8 @@ jobs:
       - name: Set up Java
         uses: actions/setup-java@v4
         with:
-          distribution: 'graalvm'
-          java-version: '21'
+          distribution: "graalvm"
+          java-version: "21"
 
       - name: Cache Gradle Packages
         uses: actions/cache@v4
@@ -93,8 +93,8 @@ jobs:
       - name: Set up Java
         uses: actions/setup-java@v4
         with:
-          distribution: 'graalvm'
-          java-version: '21'
+          distribution: "graalvm"
+          java-version: "21"
 
       - name: Cache Gradle Packages
         uses: actions/cache@v4
@@ -117,8 +117,8 @@ jobs:
       - name: Set up Java
         uses: actions/setup-java@v4
         with:
-          distribution: 'graalvm'
-          java-version: '21'
+          distribution: "graalvm"
+          java-version: "21"
 
       - name: Cache Gradle Packages
         uses: actions/cache@v4
@@ -129,8 +129,8 @@ jobs:
       - name: Run Integration Tests
         run: ./gradlew integrationTest
 
-      - uses: actions/upload-artifact@v4  # upload test results
-        if: success() || failure()        # run this step even if previous step failed
+      - uses: actions/upload-artifact@v4 # upload test results
+        if: success() || failure() # run this step even if previous step failed
         with:
           name: test-results-integration
           path: build/reports/tests/integrationTest/index.html
@@ -144,10 +144,10 @@ jobs:
     steps:
       - uses: dorny/test-reporter@v1
         with:
-          artifact: /test-results-(.*)/       # artifact name
-          name: java-junit                    # Name of the check run which will be created
-          path: '*.html'                      # Path to test results (inside artifact .zip)
-          reporter: jest-junit                # Format of test results
+          artifact: /test-results-(.*)/ # artifact name
+          name: java-junit # Name of the check run which will be created
+          path: "*.html" # Path to test results (inside artifact .zip)
+          reporter: jest-junit # Format of test results
 
   test:
     name: test end node
@@ -169,10 +169,10 @@ jobs:
       - name: Build and Deploy Quarkus Native Image
         uses: ./.github/actions/build-and-deploy-quarkus-native
         with:
-          image-name: ${{ env.IMAGE_REGISTRY }}
-          image-tag: 'amd64'
-          reg-username: ${{ github.actor }}
-          reg-token: ${{ secrets.GITHUB_TOKEN }}
+          image-name:${{ vars.DOCKER_IMAGE_NAME }}
+          image-tag: "amd64"
+          reg-username: ${{ secrets.DOCKER_USERNAME }}
+          reg-token: ${{ secrets.DOCKER_PASSWORD }}
 
   push-dockerhub-native-main-arm64:
     name: Push Native Image (ARM64)
@@ -193,10 +193,10 @@ jobs:
       - name: Build and Deploy Quarkus Native Image
         uses: ./.github/actions/build-and-deploy-quarkus-native
         with:
-          image-name: ${{ env.IMAGE_REGISTRY }}
-          image-tag: 'arm64'
-          reg-username: ${{ github.actor }}
-          reg-token: ${{ secrets.GITHUB_TOKEN }}
+          image-name:${{ vars.DOCKER_IMAGE_NAME }}
+          image-tag: "arm64"
+          reg-username: ${{ secrets.DOCKER_USERNAME }}
+          reg-token: ${{ secrets.DOCKER_PASSWORD }}
 
   docker-image-native:
     name: Docker image native
@@ -215,15 +215,15 @@ jobs:
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
       - name: Setup ARM64 Emulation
         run: |
           sudo apt-get update
           sudo apt-get install -y qemu binfmt-support qemu-user-static
           docker run --privileged --rm tonistiigi/binfmt --install all
-          
-      - run: quarkus image push --native --registry ghcr.io --registry-username=${{ github.actor }} --registry-password=${{ secrets.GITHUB_TOKEN }} --group ${{github.repository_owner}} -Dquarkus.container-image.builder=docker -D quarkus.docker.buildx.platform=linux/amd64,linux/arm64
+
+      - run: quarkus image push --native --registry ghcr.io --registry-username=${{ secrets.DOCKER_USERNAME }} --registry-password=${{ secrets.DOCKER_PASSWORD }} --group ${{github.repository_owner}} -Dquarkus.container-image.builder=docker -D quarkus.docker.buildx.platform=linux/amd64,linux/arm64
   docker-image-jvm:
     name: Docker image JVM
     runs-on: ubuntu-latest
@@ -240,8 +240,8 @@ jobs:
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
       - name: Setup ARM64 Emulation for multi arch build
         run: |
           sudo apt-get update
@@ -250,8 +250,8 @@ jobs:
       - run: |
           quarkus image push \
               --registry ghcr.io \
-              --registry-username=${{ github.actor }} \
-              --registry-password=${{ secrets.GITHUB_TOKEN }} \
+              --registry-username=${{ secrets.DOCKER_USERNAME }} \
+              --registry-password=${{ secrets.DOCKER_PASSWORD }} \
               --group ${{github.repository_owner}} \
               -Dquarkus.container-image.builder=docker \
               -D quarkus.docker.buildx.platform=linux/amd64,linux/arm64
